name: Build All

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  workflow_call:
  
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Debug, Release]
        enable_persistence: [ON, OFF]
        bnskr: [ON, OFF]
        bnslive: [ON, OFF]
        
    name: "Build ${{ matrix.build_type }} | Persistence: ${{ matrix.enable_persistence }} | BNSKR: ${{ matrix.bnskr }} | BNSLIVE: ${{ matrix.bnslive }}"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive # Ensure submodules are fetched
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git identity
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
          
    - name: Ensure Submodules are Updated
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DENABLE_PERSISTENCE=${{ matrix.enable_persistence }} -DBNSKR=${{ matrix.bnskr }} -DBNSLIVE=${{matrix.bnslive }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

